-- 데이터 유실, 보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID 순으로 조회하는 SQL문을 작성
SELECT OUTS.ANIMAL_ID AS ANIMAL_ID, OUTS.NAME AS NAME FROM ANIMAL_OUTS AS OUTS
 LEFT JOIN ANIMAL_INS AS INS ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
 WHERE INS.ANIMAL_ID IS NULL
 ORDER BY ANIMAL_ID ASC, NAME ASC;